const DATA=window.MASJID_CONFIG.defaults;let lang=localStorage.getItem("furqanLang")||"ur",timings=null,hijri=null;const order=["Fajr","Dhuhr","Asr","Maghrib","Isha"],$=id=>document.getElementById(id);
const L={ur:{welcome:"خوش آمدید",nextPrayer:"اگلی نماز",today:"آج",prayerTimes:"نماز کے اوقات",prayer:"نماز",period:"وقت",time:"ٹائم",jummah:"جمعہ",jummahSub:"نمازِ جمعہ",sundayBayan:"اتوار کا اصلاحی بیان",sundayBayanText:DATA.editable.sundayBayanUr,quranLesson:"روزانہ درسِ قرآن",quranLessonText:DATA.editable.quranLessonUr,madrasaTimes:"مدرسہ کے تعلیمی اوقات",madrasaTimesText:DATA.editable.madrasaTimesUr,ramadanCalendar:"رمضان کیلنڈر",duas:"دعائیں",commonDuas:"مسنون دعائیں",location:"مقام",findUs:"مسجد کا مقام",directions:"راستہ دیکھیں"},en:{welcome:"Welcome to",nextPrayer:"Next Prayer",today:"Today",prayerTimes:"Prayer Times",prayer:"Prayer",period:"Period",time:"Time",jummah:"Jummah",jummahSub:"Friday Prayer",sundayBayan:"Sunday Islahi Bayan",sundayBayanText:DATA.editable.sundayBayanEn,quranLesson:"Daily Quran Lesson",quranLessonText:DATA.editable.quranLessonEn,madrasaTimes:"Madrasa Timings",madrasaTimesText:DATA.editable.madrasaTimesEn,ramadanCalendar:"Ramadan Calendar",duas:"Duas",commonDuas:"Common Duas",location:"Location",findUs:"Find Us",directions:"Get Directions"}};
const N={ur:{Fajr:"فجر",Dhuhr:"ظہر",Asr:"عصر",Maghrib:"مغرب",Isha:"عشاء"},en:{Fajr:"Fajr",Dhuhr:"Dhuhr",Asr:"Asr",Maghrib:"Maghrib",Isha:"Isha"}},P={ur:{Fajr:"صبح",Dhuhr:"دوپہر",Asr:"شام",Maghrib:"شام",Isha:"رات"},en:{Fajr:"Morning",Dhuhr:"Afternoon",Asr:"Evening",Maghrib:"Evening",Isha:"Night"}};
function clean(v){return String(v||"").split(" ")[0].slice(0,5)} function show(hm){if(!hm)return"—";let[h,m]=hm.split(":").map(Number),a=h>=12?"PM":"AM";h=h%12||12;return `${h}:${String(m).padStart(2,"0")} ${a}`}
function nowK(){let p=new Intl.DateTimeFormat("en-US",{timeZone:DATA.timezone,hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).formatToParts(new Date()),o={};p.forEach(x=>o[x.type]=x.value);return{h:+o.hour,mi:+o.minute,s:+o.second}}
function secUntil(hm,tmr=false){let n=nowK(),[h,m]=hm.split(":").map(Number),s=h*3600+m*60-(n.h*3600+n.mi*60+n.s);return tmr?s+86400:s} function dur(s){s=Math.max(0,Math.floor(s));return[Math.floor(s/3600),Math.floor((s%3600)/60),s%60].map(x=>String(x).padStart(2,"0")).join(":")}
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==="ur"?"rtl":"ltr";document.querySelectorAll("[data-i18n]").forEach(el=>{let k=el.dataset.i18n;if(L[lang][k])el.textContent=L[lang][k]});$("langBtn").textContent=lang==="ur"?"EN":"UR";$("brandName").textContent=lang==="ur"?DATA.mosqueNameUr:DATA.mosqueNameEn;$("heroName").textContent=$("brandName").textContent;$("brandLoc").textContent=lang==="ur"?DATA.locationUr:DATA.locationEn;$("heroLocation").textContent=$("brandLoc").textContent;if(hijri)$("hijriDate").textContent=lang==="ur"?`${hijri.day} ${hijri.month.ar} ${hijri.year}ھ`:`${hijri.day} ${hijri.month.en} ${hijri.year} AH`; if($("madrasaDescription"))$("madrasaDescription").textContent=DATA.editable.madrasaDescription;if($("hifzDetail"))$("hifzDetail").textContent=DATA.editable.hifzDetail;if($("qaidaDetail"))$("qaidaDetail").textContent=DATA.editable.qaidaDetail;if($("donationIntro"))$("donationIntro").textContent=DATA.editable.donationIntro;if($("bankName"))$("bankName").textContent=DATA.editable.bank;if($("accountNo"))$("accountNo").textContent=DATA.editable.accountNo;if($("iban"))$("iban").textContent=DATA.editable.iban;renderDuas();if(timings)renderPrayer()}
async function loadPrayer(){try{const nowTs=Math.floor(Date.now()/1000);let u=`https://api.aladhan.com/v1/timings/${nowTs}?latitude=${DATA.latitude}&longitude=${DATA.longitude}&method=${DATA.calculationMethod}&school=${DATA.school}`;let r=await fetch(u,{cache:"no-store"}),j=await r.json();timings=j.data.timings;hijri=j.data.date.hijri;const adj=Number(DATA.hijriAdjustment||0);if(adj!==0){const shiftedTs=nowTs+(adj*86400);const hu=`https://api.aladhan.com/v1/timings/${shiftedTs}?latitude=${DATA.latitude}&longitude=${DATA.longitude}&method=${DATA.calculationMethod}&school=${DATA.school}`;const hr=await fetch(hu,{cache:"no-store"}),hj=await hr.json();if(hj?.data?.date?.hijri)hijri=hj.data.date.hijri;}applyLang();renderPrayer()}catch(e){hijri=null;renderPrayer();$("hijriDate").textContent="—"}}
function prayerTime(k){return DATA.prayerMode?.[k]==="auto"&&timings?.[k]?clean(timings[k]):DATA.jamaat[k]}
function renderPrayer(){let box=$("prayerRows");box.innerHTML="";order.forEach(k=>{let t=prayerTime(k),row=document.createElement("div");row.className="prayer-row";row.innerHTML=`<strong>${N[lang][k]}</strong><span>${P[lang][k]}</span><b>${show(t)}</b>`;box.appendChild(row)});$("jummahTime").textContent=show(DATA.jummah);let upcoming=order.map(k=>{let t=prayerTime(k);return{k,t,s:secUntil(t)}}).find(x=>x.s>0),tomorrow=false;if(!upcoming){let t=prayerTime("Fajr");upcoming={k:"Fajr",t,s:secUntil(t,true)};tomorrow=true}$("nextName").textContent=N[lang][upcoming.k];$("nextAt").textContent=(tomorrow?(lang==="ur"?"کل • ":"Tomorrow • "):"")+show(upcoming.t);$("countdown").textContent=dur(upcoming.s)}
function formatGregorian(g){const mon=(g.month&&g.month.en)?g.month.en.slice(0,3):"";return `${parseInt(g.day,10)} ${mon} ${g.year}`}
async function loadRamadan(year){try{$("ramadanStatus").textContent=lang==="ur"?"رمضان کیلنڈر لوڈ ہو رہا ہے…":"Loading Ramadan calendar…";let u=`https://api.aladhan.com/v1/hijriCalendar/${year}/9?latitude=${DATA.latitude}&longitude=${DATA.longitude}&method=${DATA.calculationMethod}&school=${DATA.school}`;let r=await fetch(u,{cache:"no-store"}),j=await r.json();if(!j.data||!Array.isArray(j.data))throw Error();let body=$("ramadanRows");body.innerHTML="";j.data.forEach(d=>{let tr=document.createElement("tr");tr.innerHTML=`<td>${d.date.hijri.day}</td><td>${formatGregorian(d.date.gregorian)}</td><td>${show(clean(d.timings.Fajr))}</td><td>${show(clean(d.timings.Maghrib))}</td>`;body.appendChild(tr)});$("ramadanStatus").textContent=lang==="ur"?`رمضان ${year}ھ • ملیر کینٹ`: `Ramadan ${year} AH • Malir Cantt`}catch(e){$("ramadanStatus").textContent=lang==="ur"?"رمضان کیلنڈر فی الحال دستیاب نہیں۔":"Ramadan calendar is currently unavailable."}}
function renderDuas(){let g=$("duasGrid");if(!g)return;g.innerHTML="";DATA.duas.forEach(d=>{let c=document.createElement("article");c.className="dua-card";c.innerHTML=`<h3>${lang==="ur"?d.titleUr:d.titleEn}</h3><div class="dua-ar" dir="rtl">${d.arabic}</div><div class="dua-trans">${lang==="ur"?d.transUr:d.transEn}</div>`;g.appendChild(c)})}
function tick(){$("clock").textContent=new Intl.DateTimeFormat("en-US",{timeZone:DATA.timezone,hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:true}).format(new Date());$("gregDate").textContent=new Intl.DateTimeFormat(lang==="ur"?"ur-PK":"en-GB",{timeZone:DATA.timezone,weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date());if(timings)renderPrayer()}
$("langBtn").onclick=()=>{lang=lang==="ur"?"en":"ur";localStorage.setItem("furqanLang",lang);applyLang()};$("mapFrame").src=DATA.map.embedUrl;$("directionsBtn").href=DATA.map.directionsUrl;applyLang();loadPrayer();tick();setInterval(tick,1000);setInterval(loadPrayer,6*60*60*1000);

window.addEventListener("masjid-data-updated",()=>{L.ur.sundayBayanText=DATA.editable.sundayBayanUr;L.en.sundayBayanText=DATA.editable.sundayBayanEn;L.ur.quranLessonText=DATA.editable.quranLessonUr;L.en.quranLessonText=DATA.editable.quranLessonEn;L.ur.madrasaTimesText=DATA.editable.madrasaTimesUr;L.en.madrasaTimesText=DATA.editable.madrasaTimesEn;applyLang();renderPrayer();});
