const DATA=window.MASJID_CONFIG.defaults;let lang=localStorage.getItem("furqanLang")||"ur",timings=null,hijri=null;const order=["Fajr","Dhuhr","Asr","Maghrib","Isha"],$=id=>document.getElementById(id);
const L={ur:{welcome:"خوش آمدید",nextPrayer:"اگلی نماز",today:"آج",prayerTimes:"نماز کے اوقات",prayer:"نماز",period:"وقت",time:"ٹائم",jummah:"جمعہ",jummahSub:"نمازِ جمعہ",sundayBayan:"اتوار کا اصلاحی بیان",sundayBayanText:"ہر اتوار نمازِ ظہر کے بعد",quranLesson:"روزانہ درسِ قرآن",quranLessonText:"روزانہ عشاء کے بعد — ترجمہ و تفسیر کے ساتھ، تقریباً 25 سے 30 منٹ",madrasaTimes:"مدرسہ کے تعلیمی اوقات",madrasaTimesText:"صبح 7:45 سے شام 4:30 تک — جمعہ ہاف ڈے، اتوار چھٹی",ramadanCalendar:"رمضان کیلنڈر",duas:"دعائیں",commonDuas:"مسنون دعائیں",location:"مقام",findUs:"مسجد کا مقام",directions:"راستہ دیکھیں"},en:{welcome:"Welcome to",nextPrayer:"Next Prayer",today:"Today",prayerTimes:"Prayer Times",prayer:"Prayer",period:"Period",time:"Time",jummah:"Jummah",jummahSub:"Friday Prayer",sundayBayan:"Sunday Islahi Bayan",sundayBayanText:"Every Sunday after Dhuhr prayer",quranLesson:"Daily Quran Lesson",quranLessonText:"Daily after Isha — translation and tafseer, approximately 25–30 minutes",madrasaTimes:"Madrasa Timings",madrasaTimesText:"7:45 AM to 4:30 PM — Friday half day, Sunday closed",ramadanCalendar:"Ramadan Calendar",duas:"Duas",commonDuas:"Common Duas",location:"Location",findUs:"Find Us",directions:"Get Directions"}};
const N={ur:{Fajr:"فجر",Dhuhr:"ظہر",Asr:"عصر",Maghrib:"مغرب",Isha:"عشاء"},en:{Fajr:"Fajr",Dhuhr:"Dhuhr",Asr:"Asr",Maghrib:"Maghrib",Isha:"Isha"}},P={ur:{Fajr:"صبح",Dhuhr:"دوپہر",Asr:"شام",Maghrib:"شام",Isha:"رات"},en:{Fajr:"Morning",Dhuhr:"Afternoon",Asr:"Evening",Maghrib:"Evening",Isha:"Night"}};
function clean(v){return String(v||"").split(" ")[0].slice(0,5)} function show(hm){if(!hm)return"—";let[h,m]=hm.split(":").map(Number),a=h>=12?"PM":"AM";h=h%12||12;return `${h}:${String(m).padStart(2,"0")} ${a}`}
function nowK(){let p=new Intl.DateTimeFormat("en-US",{timeZone:DATA.timezone,hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).formatToParts(new Date()),o={};p.forEach(x=>o[x.type]=x.value);return{h:+o.hour,mi:+o.minute,s:+o.second}}
function secUntil(hm,tmr=false){let n=nowK(),[h,m]=hm.split(":").map(Number),s=h*3600+m*60-(n.h*3600+n.mi*60+n.s);return tmr?s+86400:s} function dur(s){s=Math.max(0,Math.floor(s));return[Math.floor(s/3600),Math.floor((s%3600)/60),s%60].map(x=>String(x).padStart(2,"0")).join(":")}
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==="ur"?"rtl":"ltr";document.querySelectorAll("[data-i18n]").forEach(el=>{let k=el.dataset.i18n;if(L[lang][k])el.textContent=L[lang][k]});$("langBtn").textContent=lang==="ur"?"EN":"UR";$("brandName").textContent=lang==="ur"?DATA.mosqueNameUr:DATA.mosqueNameEn;$("heroName").textContent=$("brandName").textContent;$("brandLoc").textContent=lang==="ur"?DATA.locationUr:DATA.locationEn;$("heroLocation").textContent=$("brandLoc").textContent;if(hijri)$("hijriDate").textContent=lang==="ur"?`${hijri.day} ${hijri.month.ar} ${hijri.year}ھ`:`${hijri.day} ${hijri.month.en} ${hijri.year} AH`;renderDuas();if(timings)renderPrayer()}
async function loadPrayer(){try{let u=`https://api.aladhan.com/v1/timings/${Math.floor(Date.now()/1000)}?latitude=${DATA.latitude}&longitude=${DATA.longitude}&method=${DATA.calculationMethod}&school=${DATA.school}`;let r=await fetch(u,{cache:"no-store"}),j=await r.json();timings=j.data.timings;hijri=j.data.date.hijri;applyLang();renderPrayer();loadRamadan(hijri.year)}catch(e){hijri=null;renderPrayer();$("hijriDate").textContent="—"}}
function renderPrayer(){let box=$("prayerRows");box.innerHTML="";order.forEach(k=>{let t=DATA.jamaat[k],row=document.createElement("div");row.className="prayer-row";row.innerHTML=`<strong>${N[lang][k]}</strong><span>${P[lang][k]}</span><b>${show(t)}</b>`;box.appendChild(row)});$("jummahTime").textContent=show(DATA.jummah);let upcoming=order.map(k=>({k,t:DATA.jamaat[k],s:secUntil(DATA.jamaat[k])})).find(x=>x.s>0),tomorrow=false;if(!upcoming){upcoming={k:"Fajr",t:DATA.jamaat.Fajr,s:secUntil(DATA.jamaat.Fajr,true)};tomorrow=true}$("nextName").textContent=N[lang][upcoming.k];$("nextAt").textContent=(tomorrow?(lang==="ur"?"کل • ":"Tomorrow • "):"")+show(upcoming.t);$("countdown").textContent=dur(upcoming.s)}
async function loadRamadan(year){try{$("ramadanStatus").textContent=lang==="ur"?"رمضان کیلنڈر لوڈ ہو رہا ہے…":"Loading Ramadan calendar…";let u=`https://api.aladhan.com/v1/hijriCalendar/${year}/9?latitude=${DATA.latitude}&longitude=${DATA.longitude}&method=${DATA.calculationMethod}&school=${DATA.school}`;let r=await fetch(u,{cache:"no-store"}),j=await r.json();if(!j.data||!Array.isArray(j.data))throw Error();let body=$("ramadanRows");body.innerHTML="";j.data.forEach(d=>{let tr=document.createElement("tr");tr.innerHTML=`<td>${d.date.hijri.day}</td><td>${d.date.gregorian.date}</td><td>${show(clean(d.timings.Fajr))}</td><td>${show(clean(d.timings.Maghrib))}</td>`;body.appendChild(tr)});$("ramadanStatus").textContent=lang==="ur"?`رمضان ${year}ھ • ملیر کینٹ`: `Ramadan ${year} AH • Malir Cantt`}catch(e){$("ramadanStatus").textContent=lang==="ur"?"رمضان کیلنڈر فی الحال دستیاب نہیں۔":"Ramadan calendar is currently unavailable."}}
function renderDuas(){let g=$("duasGrid");if(!g)return;g.innerHTML="";DATA.duas.forEach(d=>{let c=document.createElement("article");c.className="dua-card";c.innerHTML=`<h3>${lang==="ur"?d.titleUr:d.titleEn}</h3><div class="dua-ar" dir="rtl">${d.arabic}</div><div class="dua-trans">${lang==="ur"?d.transUr:d.transEn}</div>`;g.appendChild(c)})}
function tick(){$("clock").textContent=new Intl.DateTimeFormat("en-US",{timeZone:DATA.timezone,hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:true}).format(new Date());$("gregDate").textContent=new Intl.DateTimeFormat(lang==="ur"?"ur-PK":"en-GB",{timeZone:DATA.timezone,weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date());if(timings)renderPrayer()}
$("langBtn").onclick=()=>{lang=lang==="ur"?"en":"ur";localStorage.setItem("furqanLang",lang);applyLang()};$("mapFrame").src=DATA.map.embedUrl;$("directionsBtn").href=DATA.map.directionsUrl;applyLang();loadPrayer();tick();setInterval(tick,1000);setInterval(loadPrayer,6*60*60*1000);
